// JsFromRoutes CacheKey 73c26414193b148d65135ad00fb0faea
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  show: /* #__PURE__ */ definePathHelper('get', '/artists/:artist_id/analytics'),
}
