// JsFromRoutes CacheKey 9699b971a92995c7adf46b4c5c1e932f
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  show: /* #__PURE__ */ definePathHelper('get', '/albums/:id'),
}
