// JsFromRoutes CacheKey db5ddb73e89c99c0a1cdd0ea113784c8
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  show: /* #__PURE__ */ definePathHelper('get', '/artists/:id'),
}
