// JsFromRoutes CacheKey f03cc8f8d95428361664753d13404144
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  play: /* #__PURE__ */ definePathHelper('post', '/tracks/:id/play'),
}
