// Typelizer digest 97b0d31146301a0cbf56ce12217526f1
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {Artist, Track} from '~/serializers'

type Album = {
  id: number;
  title: string;
  cover_url: string | null;
  artist: Artist;
  tracks?: Array<Track>;
}

export default Album;
