// Typelizer digest fc2fe9648ffa4fcd976f1ae387a55024
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {Artist, Track} from '~/serializers'

type Album = {
  id: number;
  title: string;
  cover_url: string;
  artist: Artist;
  tracks?: Array<Track>;
}

export default Album;
