// Typelizer digest 238e08888684f6e3ec2983f30cb3a460
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {ArtistAnalytics, Album, Track} from '../serializers'

type ArtistShow = {
  id: number;
  name: string;
  cover_url: string | null;
  current_listeners: number;
  analytics: ArtistAnalytics;
  albums: Array<Album>;
  tracks: Array<Track>;
}

export default ArtistShow;
