// Typelizer digest 11295533d04459b1306229fd2d1e82d4
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type Artist = {
  id: number;
  name: string;
  cover_url: string | null;
  current_listeners: number;
}

export default Artist;
