// Typelizer digest 37b489208d11d7d045599de271cf72af
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type Artist = {
  id: number;
  name: string;
  cover_url: string;
  current_listeners: number;
}

export default Artist;
