// Typelizer digest 9ae348493d93a51e57cf72c719328ae8
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {ArtistAnalytics, Album, Track} from '~/serializers'

type ArtistShow = {
  id: number;
  name: string;
  cover_url: string;
  current_listeners: number;
  analytics: ArtistAnalytics;
  albums: Array<Album>;
  tracks: Array<Track>;
}

export default ArtistShow;
