// Typelizer digest 294bcc420381ac79fcbb71d2b7fc64b4
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type ArtistAnalytics = {
  period: string;
  total: number;
}

export default ArtistAnalytics;
