// Typelizer digest 182f3db128b97871fcfcd3c4054f98fd
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {Artist, Album} from '../serializers'

type Track = {
  id: number;
  title: string;
  duration: number;
  url: string;
  artist: Artist;
  album: Album;
}

export default Track;
